# Generated by Django 4.0.2 on 2022-02-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='phone',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='employee',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
