# Generated by Django 4.0.2 on 2022-02-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_phone_store_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
