# Generated by Django 4.0.2 on 2022-02-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_visit_latitude_visit_longitude_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.store'),
        ),
    ]
